/*
  Bancos de palabras — Word Search
  =================================================================
  Dos listas planas, una por idioma, todo en mayúsculas, sin
  espacios/guiones/apóstrofes, sin acentos ni Ñ en el set español
  (para no complicar el alfabeto de la grilla ni la selección
  táctil). El generador en wordsearch.js filtra por rango de largo
  según la dificultad elegida, así que un solo array por idioma
  alcanza para las 5 dificultades.
*/

var WORDSEARCH_WORDS_EN = [
  // tech / AI
  'ROBOT', 'ALGORITHM', 'NETWORK', 'SERVER', 'BROWSER', 'INTERNET', 'SOFTWARE', 'HARDWARE',
  'DATABASE', 'ENCRYPTION', 'PROCESSOR', 'MEMORY', 'KEYBOARD', 'MONITOR', 'LAPTOP', 'TABLET',
  'SMARTPHONE', 'WIRELESS', 'BLUETOOTH', 'SATELLITE', 'ROBOTICS', 'MACHINE', 'LEARNING', 'NEURAL',
  'CIRCUIT', 'SENSOR', 'CAMERA', 'SPEAKER', 'BATTERY', 'CHARGER', 'WEBSITE', 'PLATFORM',
  'INTERFACE', 'PROGRAM', 'CODING', 'DEVELOPER', 'STARTUP', 'INNOVATION', 'DIGITAL', 'VIRTUAL',
  'ANDROID', 'CLOUD', 'DRONE', 'CHATBOT', 'AUTOMATION', 'GADGET', 'DEVICE', 'SIGNAL',
  'BANDWIDTH', 'FIREWALL', 'CODE', 'CHIP', 'DISK', 'DATA', 'ZOOM', 'LINK', 'BYTE', 'WIFI',
  // science / space
  'PLANET', 'GALAXY', 'ROCKET', 'ASTRONAUT', 'TELESCOPE', 'ORBIT', 'COMET', 'METEOR',
  'ASTEROID', 'UNIVERSE', 'GRAVITY', 'ATMOSPHERE', 'ECLIPSE', 'NEBULA', 'MOON', 'MARS',
  'SATURN', 'JUPITER', 'VENUS', 'MERCURY', 'COSMOS', 'LABORATORY', 'EXPERIMENT', 'MOLECULE',
  'ELEMENT', 'ENERGY', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'GENOME', 'VIRUS', 'VACCINE',
  'MICROSCOPE', 'RESEARCH', 'DISCOVERY', 'SPECIMEN', 'HABITAT', 'ECOSYSTEM', 'EVOLUTION',
  'DINOSAUR', 'VOLCANO', 'EARTHQUAKE', 'HURRICANE', 'GLACIER', 'RAINFOREST', 'STAR',
  // gaming
  'CONSOLE', 'JOYSTICK', 'AVATAR', 'LEVEL', 'QUEST', 'DUNGEON', 'WIZARD', 'DRAGON', 'KNIGHT',
  'CASTLE', 'TREASURE', 'ARCADE', 'PIXEL', 'CONTROLLER', 'HEADSET', 'STREAMER', 'ESPORTS',
  'VICTORY', 'PUZZLE', 'ADVENTURE', 'FANTASY', 'ZOMBIE', 'MONSTER', 'WARRIOR', 'ARCHER',
  'POTION', 'ARMOR', 'SHIELD', 'SWORD', 'MAGIC', 'SPELL', 'GOBLIN', 'PHOENIX', 'GRIFFIN',
  'LEGEND', 'MISSION', 'CHECKPOINT', 'GAME', 'JUMP',
  // entertainment
  'MOVIE', 'CINEMA', 'ACTOR', 'ACTRESS', 'DIRECTOR', 'SCRIPT', 'TRAILER', 'PREMIERE',
  'CELEBRITY', 'CONCERT', 'MUSICIAN', 'ORCHESTRA', 'MELODY', 'RHYTHM', 'PLAYLIST', 'PODCAST',
  'STUDIO', 'COSTUME', 'MAKEUP', 'THEATER', 'AUDIENCE', 'REVIEW', 'FRANCHISE', 'SEQUEL',
  'ANIMATION', 'CARTOON', 'COMEDY', 'DRAMA', 'THRILLER', 'MYSTERY', 'MUSICAL', 'BALLET',
  'FESTIVAL', 'AWARD', 'NOMINATION', 'STREAMING', 'EPISODE', 'FILM', 'SONG', 'BAND', 'TOUR',
  // sports
  'STADIUM', 'ATHLETE', 'MEDAL', 'TROPHY', 'REFEREE', 'COACH', 'TEAMWORK', 'MARATHON',
  'SPRINT', 'HURDLE', 'GYMNASTICS', 'SWIMMING', 'CYCLING', 'BASKETBALL', 'FOOTBALL', 'BASEBALL',
  'HOCKEY', 'TENNIS', 'BOXING', 'WRESTLING', 'SKATING', 'SURFING', 'CLIMBING', 'ARCHERY',
  'FENCING', 'ROWING', 'VOLLEYBALL', 'GOLF', 'TEAM', 'GOAL', 'RACE', 'CLUB', 'CHAMPION',
  'TOURNAMENT', 'STRATEGY',
  // business / social
  'INVESTOR', 'MARKET', 'PROFIT', 'REVENUE', 'BUDGET', 'MEETING', 'CONTRACT', 'PARTNER',
  'CUSTOMER', 'BRANDING', 'MARKETING', 'ADVERTISE', 'INFLUENCER', 'FOLLOWER', 'HASHTAG',
  'VIRAL', 'TRENDING', 'COMMUNITY', 'MESSAGE', 'PROFILE', 'USERNAME', 'PASSWORD', 'SUBSCRIBE',
  'COMMENT', 'FEEDBACK', 'ANALYTICS'
];

var WORDSEARCH_WORDS_ES = [
  // tecnologia / IA
  'ROBOT', 'ALGORITMO', 'INTERNET', 'SOFTWARE', 'HARDWARE', 'SERVIDOR', 'NAVEGADOR', 'TECLADO',
  'MONITOR', 'LAPTOP', 'TABLETA', 'CARGADOR', 'PANTALLA', 'PROGRAMA', 'CODIGO', 'SENSOR',
  'CAMARA', 'BATERIA', 'CIRCUITO', 'PROCESADOR', 'MEMORIA', 'ROUTER', 'SATELITE',
  'ROBOTICA', 'MAQUINA', 'NEURONAL', 'BASEDATOS', 'PLATAFORMA', 'INTERFAZ', 'DESARROLLO',
  'INNOVACION', 'DIGITAL', 'VIRTUAL', 'APARATO', 'AUTOMATICO', 'ANTENA',
  'DATOS', 'ENLACE', 'CHIP', 'DISCO', 'CORREO', 'AUDIFONO',
  // ciencia / espacio
  'PLANETA', 'GALAXIA', 'COHETE', 'ASTRONAUTA', 'TELESCOPIO', 'ORBITA', 'COMETA', 'METEORO',
  'ASTEROIDE', 'UNIVERSO', 'GRAVEDAD', 'ATMOSFERA', 'ECLIPSE', 'NEBULOSA', 'LUNA', 'MARTE',
  'SATURNO', 'JUPITER', 'VENUS', 'MERCURIO', 'COSMOS', 'PIPETA', 'PRUEBA', 'MOLECULA',
  'ELEMENTO', 'ENERGIA', 'FISICA', 'QUIMICA', 'BIOLOGIA', 'GENOMA', 'VIRUS', 'VACUNA',
  'CELULA', 'CIENCIA', 'HALLAZGO', 'ESPECIMEN', 'HABITAT', 'ECOSISTEMA',
  'EVOLUCION', 'DINOSAURIO', 'VOLCAN', 'TERREMOTO', 'HURACAN', 'GLACIAR', 'SELVA', 'ESTRELLA',
  // videojuegos
  'CONSOLA', 'AVATAR', 'NIVEL', 'MISION', 'MAZMORRA', 'MAGO', 'DRAGON', 'CABALLERO', 'CASTILLO',
  'TESORO', 'ARCADE', 'PIXEL', 'MANDO', 'AURICULAR', 'EMISION', 'VICTORIA', 'PUZLE',
  'AVENTURA', 'FANTASIA', 'ZOMBI', 'MONSTRUO', 'GUERRERO', 'ARQUERO', 'POCION', 'ARMADURA',
  'ESCUDO', 'ESPADA', 'MAGIA', 'HECHIZO', 'DUENDE', 'FENIX', 'GRIFO', 'LEYENDA', 'JUEGO',
  'SALTO', 'MUNDO', 'HEROE',
  // entretenimiento
  'PELICULA', 'CINE', 'ACTOR', 'ACTRIZ', 'DIRECTOR', 'GUION', 'TRAILER', 'ESTRENO',
  'CELEBRIDAD', 'CONCIERTO', 'MUSICO', 'ORQUESTA', 'MELODIA', 'RITMO', 'PODCAST', 'ESTUDIO',
  'VESTUARIO', 'MAQUILLAJE', 'TEATRO', 'AUDIENCIA', 'CRITICA', 'SECUELA', 'ANIMACION',
  'CARICATURA', 'COMEDIA', 'DRAMA', 'MISTERIO', 'MUSICAL', 'BALLET', 'FESTIVAL', 'PREMIO',
  'NOMINACION', 'EPISODIO', 'CANCION', 'BANDA', 'GIRA', 'ACTUACION',
  // deportes
  'ESTADIO', 'ATLETA', 'MEDALLA', 'TROFEO', 'ARBITRO', 'ENTRENADOR', 'MARATON', 'CARRERA',
  'GIMNASIA', 'NATACION', 'CICLISMO', 'BALONCESTO', 'FUTBOL', 'BEISBOL', 'HOCKEY', 'TENIS',
  'BOXEO', 'LUCHA', 'PATINAJE', 'SURF', 'ESCALADA', 'ARQUERIA', 'ESGRIMA', 'REMO', 'VOLEIBOL',
  'GOLF', 'EQUIPO', 'META', 'CLUB', 'CAMPEON', 'TORNEO', 'ESTRATEGIA', 'BALON',
  // negocios / social
  'INVERSOR', 'MERCADO', 'GANANCIA', 'FINANZAS', 'REUNION', 'CONTRATO', 'SOCIO', 'CLIENTE',
  'MARCA', 'PUBLICIDAD', 'INFLUENCER', 'SEGUIDOR', 'ETIQUETA', 'VIRAL', 'TENDENCIA',
  'COMUNIDAD', 'MENSAJE', 'PERFIL', 'USUARIO', 'CLAVE', 'SUSCRIBIR', 'COMENTARIO',
  'OPINION', 'ANALISIS'
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { WORDSEARCH_WORDS_EN: WORDSEARCH_WORDS_EN, WORDSEARCH_WORDS_ES: WORDSEARCH_WORDS_ES };
}
